import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import Navbar from "@components/Navbar/Navbar";
import ThemeProvider from "../context/ThemeProvider";
import "./globals.css";

export const monstserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "500", "600"],
});

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${monstserrat.className}`}>
        <ThemeProvider>
          <div className="flex flex-col gap-10 min-h-screen bg-white dark:bg-gray-900">
            <Navbar />
            <main className="flex flex-col gap-10">{children}</main>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
